Verification email sent to olagnascimento@gmail.comCheck if 986850 is the code sent.Exception in Tkinter callbackTraceback (most recent call last):
  File "C:\Users\nasci\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:\Users\nasci\Desktop\Code\Github\TaskFlow\imports\settings.py", line 131, in <lambda>
    command = lambda: checkCode(codeEntry.get(), loginWin),
                      ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nasci\Desktop\Code\Github\TaskFlow\imports\settings.py", line 64, in checkCode
    alert(["You are logged in.", warning], title = "Info", headings = ["Note", "Warning"])
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: alert() got an unexpected keyword argument 'headings'
Verification email sent to olagnascimento@gmail.comCheck if 040790 is the code sent.	It is.DisplayingTest task